//
//  FerryLifeStyleKit.h
//  Build with Reactive Native
//
//  Created by Mars on 2015-05-24.
//  Copyright (c) 2015 Mars Hall. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface FerryLifeStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* hiddenTerminalMarkerTargets;

// Colors
+ (UIColor*)water;
+ (UIColor*)land;
+ (UIColor*)bright;
+ (UIColor*)dark;
+ (UIColor*)vividWater;
+ (UIColor*)disabled;
+ (UIColor*)disabledAccent;
+ (UIColor*)selection;
+ (UIColor*)selectionAccent;
+ (UIColor*)background;

// Drawing Methods
+ (void)drawFerryMapWithScalePercent: (CGFloat)scalePercent;
+ (void)drawAppIcon;

// Generated Images
+ (UIImage*)imageOfTerminalMarkerWithScalePercent: (CGFloat)scalePercent;
+ (UIImage*)imageOfDisabledTerminalMarkerWithScalePercent: (CGFloat)scalePercent;
+ (UIImage*)imageOfHiddenTerminalMarker;
+ (UIImage*)imageOfSelectedTerminalMarkerWithScalePercent: (CGFloat)scalePercent;

@end
