//
//  FerryLifeStyleKit.m
//  Build with Reactive Native
//
//  Created by Mars on 2015-05-24.
//  Copyright (c) 2015 Mars Hall. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "FerryLifeStyleKit.h"


@implementation FerryLifeStyleKit

#pragma mark Cache

static UIColor* _water = nil;
static UIColor* _land = nil;
static UIColor* _bright = nil;
static UIColor* _dark = nil;
static UIColor* _vividWater = nil;
static UIColor* _disabled = nil;
static UIColor* _disabledAccent = nil;

static UIImage* _imageOfHiddenTerminalMarker = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _water = [UIColor colorWithRed: 0.447 green: 0.69 blue: 0.682 alpha: 1];
    CGFloat waterHSBA[4];
    [_water getHue: &waterHSBA[0] saturation: &waterHSBA[1] brightness: &waterHSBA[2] alpha: &waterHSBA[3]];

    _vividWater = [UIColor colorWithHue: waterHSBA[0] saturation: 0.6 brightness: waterHSBA[2] alpha: waterHSBA[3]];
    _land = [UIColor colorWithRed: 0.675 green: 0.741 blue: 0.741 alpha: 1];
    _bright = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    _dark = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 1];
    CGFloat darkHSBA[4];
    [_dark getHue: &darkHSBA[0] saturation: &darkHSBA[1] brightness: &darkHSBA[2] alpha: &darkHSBA[3]];

    _disabled = [UIColor colorWithHue: darkHSBA[0] saturation: darkHSBA[1] brightness: 0.5 alpha: darkHSBA[3]];
    CGFloat disabledHSBA[4];
    [_disabled getHue: &disabledHSBA[0] saturation: &disabledHSBA[1] brightness: &disabledHSBA[2] alpha: &disabledHSBA[3]];

    _disabledAccent = [UIColor colorWithHue: disabledHSBA[0] saturation: disabledHSBA[1] brightness: 0.8 alpha: disabledHSBA[3]];

}

#pragma mark Colors

+ (UIColor*)water { return _water; }
+ (UIColor*)land { return _land; }
+ (UIColor*)bright { return _bright; }
+ (UIColor*)dark { return _dark; }
+ (UIColor*)vividWater { return _vividWater; }
+ (UIColor*)disabled { return _disabled; }
+ (UIColor*)disabledAccent { return _disabledAccent; }

#pragma mark Drawing Methods

+ (void)drawFerryMapWithScalePercent: (CGFloat)scalePercent
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();


    //// Variable Declarations
    CGFloat scale = scalePercent * 0.01;

    //// Group
    {
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, 0, 0);
        CGContextScaleCTM(context, scale, scale);



        //// Map
        {
            CGContextSaveGState(context);
            CGContextTranslateCTM(context, 0, -0);



            //// Richmond Drawing
            UIBezierPath* richmondPath = UIBezierPath.bezierPath;
            [richmondPath moveToPoint: CGPointMake(198.33, 6.67)];
            [richmondPath addLineToPoint: CGPointMake(207, 11.34)];
            [richmondPath addLineToPoint: CGPointMake(208.33, 21.34)];
            [richmondPath addLineToPoint: CGPointMake(207, 28.67)];
            [richmondPath addLineToPoint: CGPointMake(217.67, 30)];
            [richmondPath addLineToPoint: CGPointMake(222.33, 35.34)];
            [richmondPath addLineToPoint: CGPointMake(223, 52.67)];
            [richmondPath addLineToPoint: CGPointMake(233.67, 62)];
            [richmondPath addLineToPoint: CGPointMake(247.67, 64.67)];
            [richmondPath addLineToPoint: CGPointMake(260.33, 84.67)];
            [richmondPath addLineToPoint: CGPointMake(257, 104)];
            [richmondPath addLineToPoint: CGPointMake(266.33, 107.34)];
            [richmondPath addLineToPoint: CGPointMake(270.33, 102.67)];
            [richmondPath addLineToPoint: CGPointMake(277, 106.67)];
            [richmondPath addLineToPoint: CGPointMake(293.67, 112.67)];
            [richmondPath addLineToPoint: CGPointMake(302.33, 110)];
            [richmondPath addLineToPoint: CGPointMake(310.33, 106.67)];
            [richmondPath addLineToPoint: CGPointMake(323.67, 106.67)];
            [richmondPath addLineToPoint: CGPointMake(324.67, 106.67)];
            [richmondPath addLineToPoint: CGPointMake(324.67, 3.34)];
            [richmondPath addLineToPoint: CGPointMake(198.33, 3.34)];
            [richmondPath addLineToPoint: CGPointMake(198.33, 6.67)];
            [richmondPath closePath];
            richmondPath.miterLimit = 4;

            [FerryLifeStyleKit.land setFill];
            [richmondPath fill];


            //// Marin Drawing
            UIBezierPath* marinPath = UIBezierPath.bezierPath;
            [marinPath moveToPoint: CGPointMake(19, 271.34)];
            [marinPath addLineToPoint: CGPointMake(25.67, 295.34)];
            [marinPath addLineToPoint: CGPointMake(31.67, 286)];
            [marinPath addLineToPoint: CGPointMake(44.33, 280)];
            [marinPath addLineToPoint: CGPointMake(63.67, 282.34)];
            [marinPath addLineToPoint: CGPointMake(79.17, 284.34)];
            [marinPath addLineToPoint: CGPointMake(92.67, 275.84)];
            [marinPath addLineToPoint: CGPointMake(108.17, 275.84)];
            [marinPath addLineToPoint: CGPointMake(114.67, 264.34)];
            [marinPath addLineToPoint: CGPointMake(122.17, 261.34)];
            [marinPath addLineToPoint: CGPointMake(118.67, 248.34)];
            [marinPath addLineToPoint: CGPointMake(113.17, 229.34)];
            [marinPath addLineToPoint: CGPointMake(113.17, 220.34)];
            [marinPath addLineToPoint: CGPointMake(112.67, 213.84)];
            [marinPath addLineToPoint: CGPointMake(100.67, 200.34)];
            [marinPath addLineToPoint: CGPointMake(86.17, 188.84)];
            [marinPath addLineToPoint: CGPointMake(71.17, 180.34)];
            [marinPath addLineToPoint: CGPointMake(59.67, 169.84)];
            [marinPath addLineToPoint: CGPointMake(43.17, 157.34)];
            [marinPath addLineToPoint: CGPointMake(39.17, 147.84)];
            [marinPath addLineToPoint: CGPointMake(37.67, 136.84)];
            [marinPath addLineToPoint: CGPointMake(43.67, 141.84)];
            [marinPath addLineToPoint: CGPointMake(56.67, 152.34)];
            [marinPath addLineToPoint: CGPointMake(80.17, 172.34)];
            [marinPath addLineToPoint: CGPointMake(83.17, 168.84)];
            [marinPath addLineToPoint: CGPointMake(73.67, 151.84)];
            [marinPath addLineToPoint: CGPointMake(72.17, 137.84)];
            [marinPath addLineToPoint: CGPointMake(94.17, 135.34)];
            [marinPath addLineToPoint: CGPointMake(104.17, 145.34)];
            [marinPath addLineToPoint: CGPointMake(123.17, 155.34)];
            [marinPath addLineToPoint: CGPointMake(150.17, 182.84)];
            [marinPath addLineToPoint: CGPointMake(167.67, 173.84)];
            [marinPath addLineToPoint: CGPointMake(167.67, 167.34)];
            [marinPath addLineToPoint: CGPointMake(172.17, 165.34)];
            [marinPath addLineToPoint: CGPointMake(177.67, 161.34)];
            [marinPath addLineToPoint: CGPointMake(166.67, 147.84)];
            [marinPath addLineToPoint: CGPointMake(160.67, 139.34)];
            [marinPath addLineToPoint: CGPointMake(147.67, 135.84)];
            [marinPath addLineToPoint: CGPointMake(115.67, 118.34)];
            [marinPath addLineToPoint: CGPointMake(117.17, 108.34)];
            [marinPath addLineToPoint: CGPointMake(113.67, 95.84)];
            [marinPath addLineToPoint: CGPointMake(101.67, 84.84)];
            [marinPath addLineToPoint: CGPointMake(83.17, 78.84)];
            [marinPath addLineToPoint: CGPointMake(70.67, 63.34)];
            [marinPath addLineToPoint: CGPointMake(67.17, 34.34)];
            [marinPath addLineToPoint: CGPointMake(94.17, 47.84)];
            [marinPath addLineToPoint: CGPointMake(105.17, 43.34)];
            [marinPath addLineToPoint: CGPointMake(92.82, 3.34)];
            [marinPath addLineToPoint: CGPointMake(0, 3.34)];
            [marinPath addLineToPoint: CGPointMake(0, 262.14)];
            [marinPath addLineToPoint: CGPointMake(13, 267.34)];
            [marinPath addLineToPoint: CGPointMake(19, 271.34)];
            [marinPath closePath];
            marinPath.miterLimit = 4;

            [FerryLifeStyleKit.land setFill];
            [marinPath fill];


            //// San Francisco Drawing
            UIBezierPath* sanFranciscoPath = UIBezierPath.bezierPath;
            [sanFranciscoPath moveToPoint: CGPointMake(262.33, 373.34)];
            [sanFranciscoPath addLineToPoint: CGPointMake(261.67, 362.67)];
            [sanFranciscoPath addLineToPoint: CGPointMake(259.67, 353.34)];
            [sanFranciscoPath addLineToPoint: CGPointMake(257, 344)];
            [sanFranciscoPath addLineToPoint: CGPointMake(251.67, 333.34)];
            [sanFranciscoPath addLineToPoint: CGPointMake(240.33, 323.34)];
            [sanFranciscoPath addLineToPoint: CGPointMake(235, 317.34)];
            [sanFranciscoPath addLineToPoint: CGPointMake(228.33, 312.67)];
            [sanFranciscoPath addLineToPoint: CGPointMake(213, 310.67)];
            [sanFranciscoPath addLineToPoint: CGPointMake(195, 315.34)];
            [sanFranciscoPath addLineToPoint: CGPointMake(182.33, 317.34)];
            [sanFranciscoPath addLineToPoint: CGPointMake(165.67, 314.67)];
            [sanFranciscoPath addLineToPoint: CGPointMake(150.33, 320)];
            [sanFranciscoPath addLineToPoint: CGPointMake(134.33, 320.67)];
            [sanFranciscoPath addLineToPoint: CGPointMake(128.33, 316)];
            [sanFranciscoPath addLineToPoint: CGPointMake(119.67, 311.34)];
            [sanFranciscoPath addLineToPoint: CGPointMake(113, 318.67)];
            [sanFranciscoPath addLineToPoint: CGPointMake(99, 354.67)];
            [sanFranciscoPath addLineToPoint: CGPointMake(81, 357.34)];
            [sanFranciscoPath addLineToPoint: CGPointMake(63.67, 359.34)];
            [sanFranciscoPath addLineToPoint: CGPointMake(55.67, 362.67)];
            [sanFranciscoPath addLineToPoint: CGPointMake(53, 370.67)];
            [sanFranciscoPath addLineToPoint: CGPointMake(57, 376.67)];
            [sanFranciscoPath addLineToPoint: CGPointMake(58.16, 388.67)];
            [sanFranciscoPath addLineToPoint: CGPointMake(264.56, 388.67)];
            [sanFranciscoPath addLineToPoint: CGPointMake(262.33, 383.34)];
            [sanFranciscoPath addLineToPoint: CGPointMake(262.33, 373.34)];
            [sanFranciscoPath closePath];
            sanFranciscoPath.miterLimit = 4;

            [FerryLifeStyleKit.land setFill];
            [sanFranciscoPath fill];


            //// Bay Waters Drawing
            UIBezierPath* bayWatersPath = UIBezierPath.bezierPath;
            [bayWatersPath moveToPoint: CGPointMake(58.16, 388.67)];
            [bayWatersPath addLineToPoint: CGPointMake(57, 376.67)];
            [bayWatersPath addLineToPoint: CGPointMake(53, 370.67)];
            [bayWatersPath addLineToPoint: CGPointMake(55.67, 362.67)];
            [bayWatersPath addLineToPoint: CGPointMake(63.67, 359.34)];
            [bayWatersPath addLineToPoint: CGPointMake(81, 357.34)];
            [bayWatersPath addLineToPoint: CGPointMake(99, 354.67)];
            [bayWatersPath addLineToPoint: CGPointMake(113, 318.67)];
            [bayWatersPath addLineToPoint: CGPointMake(119.67, 311.34)];
            [bayWatersPath addLineToPoint: CGPointMake(128.33, 316)];
            [bayWatersPath addLineToPoint: CGPointMake(134.33, 320.67)];
            [bayWatersPath addLineToPoint: CGPointMake(150.33, 320)];
            [bayWatersPath addLineToPoint: CGPointMake(165.67, 314.67)];
            [bayWatersPath addLineToPoint: CGPointMake(182.33, 317.34)];
            [bayWatersPath addLineToPoint: CGPointMake(195, 315.34)];
            [bayWatersPath addLineToPoint: CGPointMake(213, 310.67)];
            [bayWatersPath addLineToPoint: CGPointMake(228.33, 312.67)];
            [bayWatersPath addLineToPoint: CGPointMake(235, 317.34)];
            [bayWatersPath addLineToPoint: CGPointMake(240.33, 323.34)];
            [bayWatersPath addLineToPoint: CGPointMake(251.67, 333.34)];
            [bayWatersPath addLineToPoint: CGPointMake(257, 344)];
            [bayWatersPath addLineToPoint: CGPointMake(259.67, 353.34)];
            [bayWatersPath addLineToPoint: CGPointMake(261.67, 362.67)];
            [bayWatersPath addLineToPoint: CGPointMake(262.33, 373.34)];
            [bayWatersPath addLineToPoint: CGPointMake(262.33, 383.34)];
            [bayWatersPath addLineToPoint: CGPointMake(264.56, 388.67)];
            [bayWatersPath addLineToPoint: CGPointMake(265.67, 391.34)];
            [bayWatersPath addLineToPoint: CGPointMake(324.67, 391.34)];
            [bayWatersPath addLineToPoint: CGPointMake(324.67, 106.67)];
            [bayWatersPath addLineToPoint: CGPointMake(323.67, 106.67)];
            [bayWatersPath addLineToPoint: CGPointMake(310.33, 106.67)];
            [bayWatersPath addLineToPoint: CGPointMake(302.33, 110)];
            [bayWatersPath addLineToPoint: CGPointMake(293.67, 112.67)];
            [bayWatersPath addLineToPoint: CGPointMake(277, 106.67)];
            [bayWatersPath addLineToPoint: CGPointMake(270.33, 102.67)];
            [bayWatersPath addLineToPoint: CGPointMake(266.33, 107.34)];
            [bayWatersPath addLineToPoint: CGPointMake(257, 104)];
            [bayWatersPath addLineToPoint: CGPointMake(260.33, 84.67)];
            [bayWatersPath addLineToPoint: CGPointMake(247.67, 64.67)];
            [bayWatersPath addLineToPoint: CGPointMake(233.67, 62)];
            [bayWatersPath addLineToPoint: CGPointMake(223, 52.67)];
            [bayWatersPath addLineToPoint: CGPointMake(222.33, 35.34)];
            [bayWatersPath addLineToPoint: CGPointMake(217.67, 30)];
            [bayWatersPath addLineToPoint: CGPointMake(207, 28.67)];
            [bayWatersPath addLineToPoint: CGPointMake(208.33, 21.34)];
            [bayWatersPath addLineToPoint: CGPointMake(207, 11.34)];
            [bayWatersPath addLineToPoint: CGPointMake(198.33, 6.67)];
            [bayWatersPath addLineToPoint: CGPointMake(198.33, 3.34)];
            [bayWatersPath addLineToPoint: CGPointMake(198.33, 0)];
            [bayWatersPath addLineToPoint: CGPointMake(92.67, 2.84)];
            [bayWatersPath addLineToPoint: CGPointMake(92.82, 3.34)];
            [bayWatersPath addLineToPoint: CGPointMake(105.17, 43.34)];
            [bayWatersPath addLineToPoint: CGPointMake(94.17, 47.84)];
            [bayWatersPath addLineToPoint: CGPointMake(67.17, 34.34)];
            [bayWatersPath addLineToPoint: CGPointMake(70.67, 63.34)];
            [bayWatersPath addLineToPoint: CGPointMake(83.17, 78.84)];
            [bayWatersPath addLineToPoint: CGPointMake(101.67, 84.84)];
            [bayWatersPath addLineToPoint: CGPointMake(113.67, 95.84)];
            [bayWatersPath addLineToPoint: CGPointMake(117.17, 108.34)];
            [bayWatersPath addLineToPoint: CGPointMake(115.67, 118.34)];
            [bayWatersPath addLineToPoint: CGPointMake(147.67, 135.84)];
            [bayWatersPath addLineToPoint: CGPointMake(160.67, 139.34)];
            [bayWatersPath addLineToPoint: CGPointMake(166.67, 147.84)];
            [bayWatersPath addLineToPoint: CGPointMake(177.67, 161.34)];
            [bayWatersPath addLineToPoint: CGPointMake(172.17, 165.34)];
            [bayWatersPath addLineToPoint: CGPointMake(167.67, 167.34)];
            [bayWatersPath addLineToPoint: CGPointMake(167.67, 173.84)];
            [bayWatersPath addLineToPoint: CGPointMake(150.17, 182.84)];
            [bayWatersPath addLineToPoint: CGPointMake(123.17, 155.34)];
            [bayWatersPath addLineToPoint: CGPointMake(104.17, 145.34)];
            [bayWatersPath addLineToPoint: CGPointMake(94.17, 135.34)];
            [bayWatersPath addLineToPoint: CGPointMake(72.17, 137.84)];
            [bayWatersPath addLineToPoint: CGPointMake(73.67, 151.84)];
            [bayWatersPath addLineToPoint: CGPointMake(83.17, 168.84)];
            [bayWatersPath addLineToPoint: CGPointMake(80.17, 172.34)];
            [bayWatersPath addLineToPoint: CGPointMake(56.67, 152.34)];
            [bayWatersPath addLineToPoint: CGPointMake(43.67, 141.84)];
            [bayWatersPath addLineToPoint: CGPointMake(37.67, 136.84)];
            [bayWatersPath addLineToPoint: CGPointMake(39.17, 147.84)];
            [bayWatersPath addLineToPoint: CGPointMake(43.17, 157.34)];
            [bayWatersPath addLineToPoint: CGPointMake(59.67, 169.84)];
            [bayWatersPath addLineToPoint: CGPointMake(71.17, 180.34)];
            [bayWatersPath addLineToPoint: CGPointMake(86.17, 188.84)];
            [bayWatersPath addLineToPoint: CGPointMake(100.67, 200.34)];
            [bayWatersPath addLineToPoint: CGPointMake(112.67, 213.84)];
            [bayWatersPath addLineToPoint: CGPointMake(113.17, 220.34)];
            [bayWatersPath addLineToPoint: CGPointMake(113.17, 229.34)];
            [bayWatersPath addLineToPoint: CGPointMake(118.67, 248.34)];
            [bayWatersPath addLineToPoint: CGPointMake(122.17, 261.34)];
            [bayWatersPath addLineToPoint: CGPointMake(114.67, 264.34)];
            [bayWatersPath addLineToPoint: CGPointMake(108.17, 275.84)];
            [bayWatersPath addLineToPoint: CGPointMake(92.67, 275.84)];
            [bayWatersPath addLineToPoint: CGPointMake(79.17, 284.34)];
            [bayWatersPath addLineToPoint: CGPointMake(63.67, 282.34)];
            [bayWatersPath addLineToPoint: CGPointMake(44.33, 280)];
            [bayWatersPath addLineToPoint: CGPointMake(31.67, 286)];
            [bayWatersPath addLineToPoint: CGPointMake(25.67, 295.34)];
            [bayWatersPath addLineToPoint: CGPointMake(19, 271.34)];
            [bayWatersPath addLineToPoint: CGPointMake(13, 267.34)];
            [bayWatersPath addLineToPoint: CGPointMake(0, 262.14)];
            [bayWatersPath addLineToPoint: CGPointMake(0, 397.34)];
            [bayWatersPath addLineToPoint: CGPointMake(59, 397.34)];
            [bayWatersPath addLineToPoint: CGPointMake(58.16, 388.67)];
            [bayWatersPath closePath];
            bayWatersPath.miterLimit = 4;

            [FerryLifeStyleKit.water setFill];
            [bayWatersPath fill];


            //// SF Bay label Drawing
            CGRect sFBayLabelRect = CGRectMake(208, 123.84, 107, 36);
            {
                NSString* textContent = @"San Franscisco Bay";
                NSMutableParagraphStyle* sFBayLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
                sFBayLabelStyle.alignment = NSTextAlignmentCenter;

                NSDictionary* sFBayLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.bright, NSParagraphStyleAttributeName: sFBayLabelStyle};

                CGFloat sFBayLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(sFBayLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: sFBayLabelFontAttributes context: nil].size.height;
                CGContextSaveGState(context);
                CGContextClipToRect(context, sFBayLabelRect);
                [textContent drawInRect: CGRectMake(CGRectGetMinX(sFBayLabelRect), CGRectGetMinY(sFBayLabelRect) + (CGRectGetHeight(sFBayLabelRect) - sFBayLabelTextHeight) / 2, CGRectGetWidth(sFBayLabelRect), sFBayLabelTextHeight) withAttributes: sFBayLabelFontAttributes];
                CGContextRestoreGState(context);
            }


            //// Pacific Ocean label Drawing
            CGRect pacificOceanLabelRect = CGRectMake(0, 310.84, 107, 36);
            {
                NSString* textContent = @"Pacific Ocean";
                NSMutableParagraphStyle* pacificOceanLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
                pacificOceanLabelStyle.alignment = NSTextAlignmentCenter;

                NSDictionary* pacificOceanLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.bright, NSParagraphStyleAttributeName: pacificOceanLabelStyle};

                CGFloat pacificOceanLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(pacificOceanLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: pacificOceanLabelFontAttributes context: nil].size.height;
                CGContextSaveGState(context);
                CGContextClipToRect(context, pacificOceanLabelRect);
                [textContent drawInRect: CGRectMake(CGRectGetMinX(pacificOceanLabelRect), CGRectGetMinY(pacificOceanLabelRect) + (CGRectGetHeight(pacificOceanLabelRect) - pacificOceanLabelTextHeight) / 2, CGRectGetWidth(pacificOceanLabelRect), pacificOceanLabelTextHeight) withAttributes: pacificOceanLabelFontAttributes];
                CGContextRestoreGState(context);
            }


            //// San Francisco label Drawing
            CGRect sanFranciscoLabelRect = CGRectMake(109, 352.84, 107, 36);
            {
                NSString* textContent = @"San Francisco";
                NSMutableParagraphStyle* sanFranciscoLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
                sanFranciscoLabelStyle.alignment = NSTextAlignmentCenter;

                NSDictionary* sanFranciscoLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.bright, NSParagraphStyleAttributeName: sanFranciscoLabelStyle};

                CGFloat sanFranciscoLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(sanFranciscoLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: sanFranciscoLabelFontAttributes context: nil].size.height;
                CGContextSaveGState(context);
                CGContextClipToRect(context, sanFranciscoLabelRect);
                [textContent drawInRect: CGRectMake(CGRectGetMinX(sanFranciscoLabelRect), CGRectGetMinY(sanFranciscoLabelRect) + (CGRectGetHeight(sanFranciscoLabelRect) - sanFranciscoLabelTextHeight) / 2, CGRectGetWidth(sanFranciscoLabelRect), sanFranciscoLabelTextHeight) withAttributes: sanFranciscoLabelFontAttributes];
                CGContextRestoreGState(context);
            }


            //// Marin label Drawing
            CGRect marinLabelRect = CGRectMake(0, 87.84, 107, 36);
            {
                NSString* textContent = @"Marin";
                NSMutableParagraphStyle* marinLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
                marinLabelStyle.alignment = NSTextAlignmentCenter;

                NSDictionary* marinLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.bright, NSParagraphStyleAttributeName: marinLabelStyle};

                CGFloat marinLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(marinLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: marinLabelFontAttributes context: nil].size.height;
                CGContextSaveGState(context);
                CGContextClipToRect(context, marinLabelRect);
                [textContent drawInRect: CGRectMake(CGRectGetMinX(marinLabelRect), CGRectGetMinY(marinLabelRect) + (CGRectGetHeight(marinLabelRect) - marinLabelTextHeight) / 2, CGRectGetWidth(marinLabelRect), marinLabelTextHeight) withAttributes: marinLabelFontAttributes];
                CGContextRestoreGState(context);
            }



            CGContextRestoreGState(context);
        }


        //// Routes
        {
            CGContextSaveGState(context);
            CGContextTranslateCTM(context, 0, -0);



            //// Larkspur-Ferry-Bldg route Drawing
            UIBezierPath* larkspurFerryBldgRoutePath = UIBezierPath.bezierPath;
            [larkspurFerryBldgRoutePath moveToPoint: CGPointMake(81.17, 47.33)];
            [larkspurFerryBldgRoutePath addLineToPoint: CGPointMake(258.83, 225)];
            [larkspurFerryBldgRoutePath addLineToPoint: CGPointMake(258.83, 323.33)];
            larkspurFerryBldgRoutePath.miterLimit = 4;

            [FerryLifeStyleKit.disabled setStroke];
            larkspurFerryBldgRoutePath.lineWidth = 4;
            [larkspurFerryBldgRoutePath stroke];


            //// Sausalito-Ferry-Bldg route Drawing
            UIBezierPath* sausalitoFerryBldgRoutePath = UIBezierPath.bezierPath;
            [sausalitoFerryBldgRoutePath moveToPoint: CGPointMake(253.17, 320.5)];
            [sausalitoFerryBldgRoutePath addLineToPoint: CGPointMake(253.17, 279)];
            [sausalitoFerryBldgRoutePath addLineToPoint: CGPointMake(177.17, 203)];
            [sausalitoFerryBldgRoutePath addLineToPoint: CGPointMake(113.67, 203)];
            sausalitoFerryBldgRoutePath.miterLimit = 4;

            [FerryLifeStyleKit.disabled setStroke];
            sausalitoFerryBldgRoutePath.lineWidth = 4;
            [sausalitoFerryBldgRoutePath stroke];


            //// Sausalito-Pier-41 route Drawing
            UIBezierPath* sausalitoPier41RoutePath = UIBezierPath.bezierPath;
            [sausalitoPier41RoutePath moveToPoint: CGPointMake(113.17, 208.5)];
            [sausalitoPier41RoutePath addLineToPoint: CGPointMake(158.67, 208.5)];
            [sausalitoPier41RoutePath addLineToPoint: CGPointMake(207.92, 257.75)];
            [sausalitoPier41RoutePath addLineToPoint: CGPointMake(207.92, 300.5)];
            sausalitoPier41RoutePath.miterLimit = 4;

            [FerryLifeStyleKit.disabled setStroke];
            sausalitoPier41RoutePath.lineWidth = 4;
            [sausalitoPier41RoutePath stroke];


            //// Sausalito-Tiburon route Drawing
            UIBezierPath* sausalitoTiburonRoutePath = UIBezierPath.bezierPath;
            [sausalitoTiburonRoutePath moveToPoint: CGPointMake(113.67, 197.5)];
            [sausalitoTiburonRoutePath addLineToPoint: CGPointMake(131.17, 197.5)];
            [sausalitoTiburonRoutePath addLineToPoint: CGPointMake(137.42, 191.25)];
            sausalitoTiburonRoutePath.miterLimit = 4;

            [FerryLifeStyleKit.disabled setStroke];
            sausalitoTiburonRoutePath.lineWidth = 4;
            [sausalitoTiburonRoutePath stroke];


            //// Tiburon-Ferry-Bldg route Drawing
            UIBezierPath* tiburonFerryBldgRoutePath = UIBezierPath.bezierPath;
            [tiburonFerryBldgRoutePath moveToPoint: CGPointMake(157.17, 191)];
            [tiburonFerryBldgRoutePath addLineToPoint: CGPointMake(247.67, 281.5)];
            [tiburonFerryBldgRoutePath addLineToPoint: CGPointMake(247.67, 322)];
            tiburonFerryBldgRoutePath.miterLimit = 4;

            [FerryLifeStyleKit.dark setStroke];
            tiburonFerryBldgRoutePath.lineWidth = 4;
            [tiburonFerryBldgRoutePath stroke];


            //// Tiburon-Pier-41 route Drawing
            UIBezierPath* tiburonPier41RoutePath = UIBezierPath.bezierPath;
            [tiburonPier41RoutePath moveToPoint: CGPointMake(153.17, 195)];
            [tiburonPier41RoutePath addLineToPoint: CGPointMake(213.42, 255.25)];
            [tiburonPier41RoutePath addLineToPoint: CGPointMake(213.42, 301)];
            tiburonPier41RoutePath.miterLimit = 4;

            [FerryLifeStyleKit.dark setStroke];
            tiburonPier41RoutePath.lineWidth = 4;
            [tiburonPier41RoutePath stroke];



            CGContextRestoreGState(context);
        }


        //// Terminals
        {
            CGContextSaveGState(context);



            //// Sausalito marker Drawing
            CGRect sausalitoMarkerRect = CGRectMake(80, 181, 44, 44);
            CGContextSaveGState(context);
            UIRectClip(sausalitoMarkerRect);
            CGContextTranslateCTM(context, sausalitoMarkerRect.origin.x, sausalitoMarkerRect.origin.y);

            [FerryLifeStyleKit drawDisabledTerminalMarkerWithScalePercent: 100];
            CGContextRestoreGState(context);


            //// Sausalito label Drawing
            CGRect sausalitoLabelRect = CGRectMake(33, 186, 51, 29);
            {
                NSString* textContent = @"Sausalito";
                NSMutableParagraphStyle* sausalitoLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
                sausalitoLabelStyle.alignment = NSTextAlignmentRight;

                NSDictionary* sausalitoLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.disabled, NSParagraphStyleAttributeName: sausalitoLabelStyle};

                CGFloat sausalitoLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(sausalitoLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: sausalitoLabelFontAttributes context: nil].size.height;
                CGContextSaveGState(context);
                CGContextClipToRect(context, sausalitoLabelRect);
                [textContent drawInRect: CGRectMake(CGRectGetMinX(sausalitoLabelRect), CGRectGetMinY(sausalitoLabelRect) + (CGRectGetHeight(sausalitoLabelRect) - sausalitoLabelTextHeight) / 2, CGRectGetWidth(sausalitoLabelRect), sausalitoLabelTextHeight) withAttributes: sausalitoLabelFontAttributes];
                CGContextRestoreGState(context);
            }


            //// Larkspur marker Drawing
            CGRect larkspurMarkerRect = CGRectMake(50, 17, 44, 44);
            CGContextSaveGState(context);
            UIRectClip(larkspurMarkerRect);
            CGContextTranslateCTM(context, larkspurMarkerRect.origin.x, larkspurMarkerRect.origin.y);

            [FerryLifeStyleKit drawDisabledTerminalMarkerWithScalePercent: 100];
            CGContextRestoreGState(context);


            //// Larkspur label Drawing
            CGRect larkspurLabelRect = CGRectMake(2, 18, 51, 29);
            {
                NSString* textContent = @"Larkspur";
                NSMutableParagraphStyle* larkspurLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
                larkspurLabelStyle.alignment = NSTextAlignmentRight;

                NSDictionary* larkspurLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.disabled, NSParagraphStyleAttributeName: larkspurLabelStyle};

                CGFloat larkspurLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(larkspurLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: larkspurLabelFontAttributes context: nil].size.height;
                CGContextSaveGState(context);
                CGContextClipToRect(context, larkspurLabelRect);
                [textContent drawInRect: CGRectMake(CGRectGetMinX(larkspurLabelRect), CGRectGetMinY(larkspurLabelRect) + (CGRectGetHeight(larkspurLabelRect) - larkspurLabelTextHeight) / 2, CGRectGetWidth(larkspurLabelRect), larkspurLabelTextHeight) withAttributes: larkspurLabelFontAttributes];
                CGContextRestoreGState(context);
            }


            //// Tiburon marker Drawing
            CGRect tiburonMarkerRect = CGRectMake(124, 162, 44, 44);
            CGContextSaveGState(context);
            UIRectClip(tiburonMarkerRect);
            CGContextTranslateCTM(context, tiburonMarkerRect.origin.x, tiburonMarkerRect.origin.y);

            [FerryLifeStyleKit drawHiddenTerminalMarker];
            CGContextRestoreGState(context);


            //// Tiburon label Drawing
            CGRect tiburonLabelRect = CGRectMake(79, 161, 51, 29);
            {
                NSString* textContent = @"Tiburon";
                NSMutableParagraphStyle* tiburonLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
                tiburonLabelStyle.alignment = NSTextAlignmentRight;

                NSDictionary* tiburonLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.dark, NSParagraphStyleAttributeName: tiburonLabelStyle};

                CGFloat tiburonLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(tiburonLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: tiburonLabelFontAttributes context: nil].size.height;
                CGContextSaveGState(context);
                CGContextClipToRect(context, tiburonLabelRect);
                [textContent drawInRect: CGRectMake(CGRectGetMinX(tiburonLabelRect), CGRectGetMinY(tiburonLabelRect) + (CGRectGetHeight(tiburonLabelRect) - tiburonLabelTextHeight) / 2, CGRectGetWidth(tiburonLabelRect), tiburonLabelTextHeight) withAttributes: tiburonLabelFontAttributes];
                CGContextRestoreGState(context);
            }


            //// Pier 41 marker Drawing
            CGRect pier41MarkerRect = CGRectMake(188, 291, 44, 44);
            CGContextSaveGState(context);
            UIRectClip(pier41MarkerRect);
            CGContextTranslateCTM(context, pier41MarkerRect.origin.x, pier41MarkerRect.origin.y);

            [FerryLifeStyleKit drawHiddenTerminalMarker];
            CGContextRestoreGState(context);


            //// Pier 41 label Drawing
            CGRect pier41LabelRect = CGRectMake(143, 304, 51, 29);
            {
                NSString* textContent = @"Pier 41";
                NSMutableParagraphStyle* pier41LabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
                pier41LabelStyle.alignment = NSTextAlignmentRight;

                NSDictionary* pier41LabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.dark, NSParagraphStyleAttributeName: pier41LabelStyle};

                CGFloat pier41LabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(pier41LabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: pier41LabelFontAttributes context: nil].size.height;
                CGContextSaveGState(context);
                CGContextClipToRect(context, pier41LabelRect);
                [textContent drawInRect: CGRectMake(CGRectGetMinX(pier41LabelRect), CGRectGetMinY(pier41LabelRect) + (CGRectGetHeight(pier41LabelRect) - pier41LabelTextHeight) / 2, CGRectGetWidth(pier41LabelRect), pier41LabelTextHeight) withAttributes: pier41LabelFontAttributes];
                CGContextRestoreGState(context);
            }


            //// Ferry Bldg marker Drawing
            CGRect ferryBldgMarkerRect = CGRectMake(231, 312, 44, 44);
            CGContextSaveGState(context);
            UIRectClip(ferryBldgMarkerRect);
            CGContextTranslateCTM(context, ferryBldgMarkerRect.origin.x, ferryBldgMarkerRect.origin.y);

            [FerryLifeStyleKit drawHiddenTerminalMarker];
            CGContextRestoreGState(context);


            //// Ferry Bldg label Drawing
            CGRect ferryBldgLabelRect = CGRectMake(186, 325, 51, 29);
            {
                NSString* textContent = @"Ferry Bldg";
                NSMutableParagraphStyle* ferryBldgLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
                ferryBldgLabelStyle.alignment = NSTextAlignmentRight;

                NSDictionary* ferryBldgLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.dark, NSParagraphStyleAttributeName: ferryBldgLabelStyle};

                CGFloat ferryBldgLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(ferryBldgLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: ferryBldgLabelFontAttributes context: nil].size.height;
                CGContextSaveGState(context);
                CGContextClipToRect(context, ferryBldgLabelRect);
                [textContent drawInRect: CGRectMake(CGRectGetMinX(ferryBldgLabelRect), CGRectGetMinY(ferryBldgLabelRect) + (CGRectGetHeight(ferryBldgLabelRect) - ferryBldgLabelTextHeight) / 2, CGRectGetWidth(ferryBldgLabelRect), ferryBldgLabelTextHeight) withAttributes: ferryBldgLabelFontAttributes];
                CGContextRestoreGState(context);
            }



            CGContextRestoreGState(context);
        }



        CGContextRestoreGState(context);
    }
}

+ (void)drawTerminalMarkerWithScalePercent: (CGFloat)scalePercent
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();


    //// Variable Declarations
    CGFloat scale = scalePercent * 0.01;

    //// disc Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 22.5, 21.5);
    CGContextScaleCTM(context, scale, scale);

    UIBezierPath* discPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(-12.5, -12.5, 25, 25)];
    [FerryLifeStyleKit.bright setFill];
    [discPath fill];
    [FerryLifeStyleKit.dark setStroke];
    discPath.lineWidth = 4;
    [discPath stroke];

    CGContextRestoreGState(context);
}

+ (void)drawDisabledTerminalMarkerWithScalePercent: (CGFloat)scalePercent
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();


    //// Variable Declarations
    CGFloat scale = scalePercent * 0.01;

    //// disc Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 22.5, 21.5);
    CGContextScaleCTM(context, scale, scale);

    UIBezierPath* discPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(-12.5, -12.5, 25, 25)];
    [FerryLifeStyleKit.disabledAccent setFill];
    [discPath fill];
    [FerryLifeStyleKit.disabled setStroke];
    discPath.lineWidth = 4;
    [discPath stroke];

    CGContextRestoreGState(context);
}

+ (void)drawHiddenTerminalMarker
{
}

+ (void)drawSelectedTerminalMarkerWithScalePercent: (CGFloat)scalePercent
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* selection = [UIColor colorWithRed: 1 green: 0.487 blue: 0 alpha: 1];
    CGFloat selectionHSBA[4];
    [selection getHue: &selectionHSBA[0] saturation: &selectionHSBA[1] brightness: &selectionHSBA[2] alpha: &selectionHSBA[3]];

    UIColor* selectionAccent = [UIColor colorWithHue: selectionHSBA[0] saturation: 0.3 brightness: selectionHSBA[2] alpha: selectionHSBA[3]];

    //// Variable Declarations
    CGFloat scale = scalePercent * 0.01;

    //// disc Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 22.5, 21.5);
    CGContextScaleCTM(context, scale, scale);

    UIBezierPath* discPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(-12.5, -12.5, 25, 25)];
    [selectionAccent setFill];
    [discPath fill];
    [selection setStroke];
    discPath.lineWidth = 4;
    [discPath stroke];

    CGContextRestoreGState(context);
}

+ (void)drawAppIcon
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Group
    {
        //// Map
        {
            //// San Francisco Drawing
            UIBezierPath* sanFranciscoPath = UIBezierPath.bezierPath;
            [sanFranciscoPath moveToPoint: CGPointMake(889.63, 938.77)];
            [sanFranciscoPath addLineToPoint: CGPointMake(885.25, 868.66)];
            [sanFranciscoPath addLineToPoint: CGPointMake(872.1, 807.33)];
            [sanFranciscoPath addLineToPoint: CGPointMake(854.55, 745.99)];
            [sanFranciscoPath addLineToPoint: CGPointMake(819.47, 675.88)];
            [sanFranciscoPath addLineToPoint: CGPointMake(744.92, 610.16)];
            [sanFranciscoPath addLineToPoint: CGPointMake(709.84, 570.73)];
            [sanFranciscoPath addLineToPoint: CGPointMake(665.98, 540.06)];
            [sanFranciscoPath addLineToPoint: CGPointMake(565.12, 526.91)];
            [sanFranciscoPath addLineToPoint: CGPointMake(446.71, 557.58)];
            [sanFranciscoPath addLineToPoint: CGPointMake(363.4, 570.73)];
            [sanFranciscoPath addLineToPoint: CGPointMake(253.76, 553.2)];
            [sanFranciscoPath addLineToPoint: CGPointMake(152.9, 588.26)];
            [sanFranciscoPath addLineToPoint: CGPointMake(47.65, 592.63)];
            [sanFranciscoPath addLineToPoint: CGPointMake(8.18, 561.97)];
            [sanFranciscoPath addLineToPoint: CGPointMake(-48.83, 531.3)];
            [sanFranciscoPath addLineToPoint: CGPointMake(-92.68, 579.49)];
            [sanFranciscoPath addLineToPoint: CGPointMake(-184.78, 816.09)];
            [sanFranciscoPath addLineToPoint: CGPointMake(-303.18, 833.61)];
            [sanFranciscoPath addLineToPoint: CGPointMake(-417.2, 846.76)];
            [sanFranciscoPath addLineToPoint: CGPointMake(-469.82, 868.66)];
            [sanFranciscoPath addLineToPoint: CGPointMake(-487.36, 921.24)];
            [sanFranciscoPath addLineToPoint: CGPointMake(-461.05, 960.67)];
            [sanFranciscoPath addLineToPoint: CGPointMake(-453.41, 1039.54)];
            [sanFranciscoPath addLineToPoint: CGPointMake(904.26, 1039.54)];
            [sanFranciscoPath addLineToPoint: CGPointMake(889.63, 1004.49)];
            [sanFranciscoPath addLineToPoint: CGPointMake(889.63, 938.77)];
            [sanFranciscoPath closePath];
            sanFranciscoPath.miterLimit = 4;

            [FerryLifeStyleKit.land setFill];
            [sanFranciscoPath fill];


            //// Bay Waters Drawing
            UIBezierPath* bayWatersPath = UIBezierPath.bezierPath;
            [bayWatersPath moveToPoint: CGPointMake(-453.41, 1053.54)];
            [bayWatersPath addLineToPoint: CGPointMake(-461.05, 974.67)];
            [bayWatersPath addLineToPoint: CGPointMake(-487.36, 935.24)];
            [bayWatersPath addLineToPoint: CGPointMake(-469.82, 882.66)];
            [bayWatersPath addLineToPoint: CGPointMake(-417.2, 860.76)];
            [bayWatersPath addLineToPoint: CGPointMake(-303.18, 847.61)];
            [bayWatersPath addLineToPoint: CGPointMake(-184.78, 830.09)];
            [bayWatersPath addLineToPoint: CGPointMake(-92.68, 593.49)];
            [bayWatersPath addLineToPoint: CGPointMake(-48.83, 545.3)];
            [bayWatersPath addLineToPoint: CGPointMake(8.18, 575.97)];
            [bayWatersPath addLineToPoint: CGPointMake(47.65, 606.63)];
            [bayWatersPath addLineToPoint: CGPointMake(152.9, 602.26)];
            [bayWatersPath addLineToPoint: CGPointMake(253.76, 567.2)];
            [bayWatersPath addLineToPoint: CGPointMake(363.4, 584.73)];
            [bayWatersPath addLineToPoint: CGPointMake(446.71, 571.58)];
            [bayWatersPath addLineToPoint: CGPointMake(565.12, 540.91)];
            [bayWatersPath addLineToPoint: CGPointMake(665.98, 554.06)];
            [bayWatersPath addLineToPoint: CGPointMake(709.84, 584.73)];
            [bayWatersPath addLineToPoint: CGPointMake(744.92, 624.16)];
            [bayWatersPath addLineToPoint: CGPointMake(819.47, 689.88)];
            [bayWatersPath addLineToPoint: CGPointMake(854.55, 759.99)];
            [bayWatersPath addLineToPoint: CGPointMake(872.1, 821.33)];
            [bayWatersPath addLineToPoint: CGPointMake(885.25, 882.66)];
            [bayWatersPath addLineToPoint: CGPointMake(889.63, 952.77)];
            [bayWatersPath addLineToPoint: CGPointMake(889.63, 1018.49)];
            [bayWatersPath addLineToPoint: CGPointMake(904.26, 1053.54)];
            [bayWatersPath addLineToPoint: CGPointMake(911.56, 1071.07)];
            [bayWatersPath addLineToPoint: CGPointMake(1299.67, 1071.07)];
            [bayWatersPath addLineToPoint: CGPointMake(1299.67, -799.81)];
            [bayWatersPath addLineToPoint: CGPointMake(1293.09, -799.81)];
            [bayWatersPath addLineToPoint: CGPointMake(1205.38, -799.81)];
            [bayWatersPath addLineToPoint: CGPointMake(1152.76, -777.9)];
            [bayWatersPath addLineToPoint: CGPointMake(1095.75, -760.37)];
            [bayWatersPath addLineToPoint: CGPointMake(986.11, -799.81)];
            [bayWatersPath addLineToPoint: CGPointMake(942.26, -826.09)];
            [bayWatersPath addLineToPoint: CGPointMake(915.94, -795.42)];
            [bayWatersPath addLineToPoint: CGPointMake(854.55, -817.33)];
            [bayWatersPath addLineToPoint: CGPointMake(876.48, -944.39)];
            [bayWatersPath addLineToPoint: CGPointMake(793.16, -1075.83)];
            [bayWatersPath addLineToPoint: CGPointMake(701.07, -1093.36)];
            [bayWatersPath addLineToPoint: CGPointMake(630.9, -1154.7)];
            [bayWatersPath addLineToPoint: CGPointMake(626.51, -1268.62)];
            [bayWatersPath addLineToPoint: CGPointMake(595.82, -1303.67)];
            [bayWatersPath addLineToPoint: CGPointMake(525.65, -1312.43)];
            [bayWatersPath addLineToPoint: CGPointMake(534.42, -1360.63)];
            [bayWatersPath addLineToPoint: CGPointMake(525.65, -1426.35)];
            [bayWatersPath addLineToPoint: CGPointMake(468.64, -1457.02)];
            [bayWatersPath addLineToPoint: CGPointMake(468.64, -1478.93)];
            [bayWatersPath addLineToPoint: CGPointMake(468.64, -1500.83)];
            [bayWatersPath addLineToPoint: CGPointMake(-226.43, -1482.22)];
            [bayWatersPath addLineToPoint: CGPointMake(-225.42, -1478.93)];
            [bayWatersPath addLineToPoint: CGPointMake(-144.21, -1216.05)];
            [bayWatersPath addLineToPoint: CGPointMake(-216.57, -1186.47)];
            [bayWatersPath addLineToPoint: CGPointMake(-394.17, -1275.2)];
            [bayWatersPath addLineToPoint: CGPointMake(-371.15, -1084.6)];
            [bayWatersPath addLineToPoint: CGPointMake(-288.93, -982.74)];
            [bayWatersPath addLineToPoint: CGPointMake(-167.23, -943.3)];
            [bayWatersPath addLineToPoint: CGPointMake(-88.3, -871.01)];
            [bayWatersPath addLineToPoint: CGPointMake(-65.27, -788.86)];
            [bayWatersPath addLineToPoint: CGPointMake(-75.14, -723.14)];
            [bayWatersPath addLineToPoint: CGPointMake(135.36, -608.12)];
            [bayWatersPath addLineToPoint: CGPointMake(220.87, -585.12)];
            [bayWatersPath addLineToPoint: CGPointMake(260.34, -529.26)];
            [bayWatersPath addLineToPoint: CGPointMake(332.7, -440.53)];
            [bayWatersPath addLineToPoint: CGPointMake(296.52, -414.24)];
            [bayWatersPath addLineToPoint: CGPointMake(266.92, -401.1)];
            [bayWatersPath addLineToPoint: CGPointMake(266.92, -358.38)];
            [bayWatersPath addLineToPoint: CGPointMake(151.8, -299.23)];
            [bayWatersPath addLineToPoint: CGPointMake(-25.8, -479.97)];
            [bayWatersPath addLineToPoint: CGPointMake(-150.79, -545.69)];
            [bayWatersPath addLineToPoint: CGPointMake(-216.57, -611.41)];
            [bayWatersPath addLineToPoint: CGPointMake(-361.28, -594.98)];
            [bayWatersPath addLineToPoint: CGPointMake(-351.42, -502.97)];
            [bayWatersPath addLineToPoint: CGPointMake(-288.93, -391.24)];
            [bayWatersPath addLineToPoint: CGPointMake(-308.66, -368.24)];
            [bayWatersPath addLineToPoint: CGPointMake(-463.24, -499.68)];
            [bayWatersPath addLineToPoint: CGPointMake(-548.76, -568.69)];
            [bayWatersPath addLineToPoint: CGPointMake(-588.23, -601.55)];
            [bayWatersPath addLineToPoint: CGPointMake(-578.36, -529.26)];
            [bayWatersPath addLineToPoint: CGPointMake(-552.05, -466.82)];
            [bayWatersPath addLineToPoint: CGPointMake(-443.51, -384.67)];
            [bayWatersPath addLineToPoint: CGPointMake(-367.86, -315.66)];
            [bayWatersPath addLineToPoint: CGPointMake(-269.19, -259.8)];
            [bayWatersPath addLineToPoint: CGPointMake(-173.81, -184.22)];
            [bayWatersPath addLineToPoint: CGPointMake(-94.87, -95.5)];
            [bayWatersPath addLineToPoint: CGPointMake(-91.58, -52.78)];
            [bayWatersPath addLineToPoint: CGPointMake(-91.58, 6.37)];
            [bayWatersPath addLineToPoint: CGPointMake(-55.41, 131.24)];
            [bayWatersPath addLineToPoint: CGPointMake(-32.38, 216.68)];
            [bayWatersPath addLineToPoint: CGPointMake(-81.72, 236.4)];
            [bayWatersPath addLineToPoint: CGPointMake(-124.47, 311.98)];
            [bayWatersPath addLineToPoint: CGPointMake(-226.43, 311.98)];
            [bayWatersPath addLineToPoint: CGPointMake(-315.24, 367.84)];
            [bayWatersPath addLineToPoint: CGPointMake(-417.2, 354.7)];
            [bayWatersPath addLineToPoint: CGPointMake(-544.38, 339.37)];
            [bayWatersPath addLineToPoint: CGPointMake(-627.69, 378.8)];
            [bayWatersPath addLineToPoint: CGPointMake(-667.16, 440.14)];
            [bayWatersPath addLineToPoint: CGPointMake(-711.02, 282.41)];
            [bayWatersPath addLineToPoint: CGPointMake(-750.49, 256.12)];
            [bayWatersPath addLineToPoint: CGPointMake(-836, 221.95)];
            [bayWatersPath addLineToPoint: CGPointMake(-836, 1110.5)];
            [bayWatersPath addLineToPoint: CGPointMake(-447.9, 1110.5)];
            [bayWatersPath addLineToPoint: CGPointMake(-453.41, 1053.54)];
            [bayWatersPath closePath];
            bayWatersPath.miterLimit = 4;

            [FerryLifeStyleKit.water setFill];
            [bayWatersPath fill];


            //// San Francisco label Drawing
            CGRect sanFranciscoLabelRect = CGRectMake(58, 763, 705, 240);
            {
                NSString* textContent = @"San Francisco";
                NSMutableParagraphStyle* sanFranciscoLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
                sanFranciscoLabelStyle.alignment = NSTextAlignmentCenter;

                NSDictionary* sanFranciscoLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: 100], NSForegroundColorAttributeName: FerryLifeStyleKit.bright, NSParagraphStyleAttributeName: sanFranciscoLabelStyle};

                CGFloat sanFranciscoLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(sanFranciscoLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: sanFranciscoLabelFontAttributes context: nil].size.height;
                CGContextSaveGState(context);
                CGContextClipToRect(context, sanFranciscoLabelRect);
                [textContent drawInRect: CGRectMake(CGRectGetMinX(sanFranciscoLabelRect), CGRectGetMinY(sanFranciscoLabelRect) + (CGRectGetHeight(sanFranciscoLabelRect) - sanFranciscoLabelTextHeight) / 2, CGRectGetWidth(sanFranciscoLabelRect), sanFranciscoLabelTextHeight) withAttributes: sanFranciscoLabelFontAttributes];
                CGContextRestoreGState(context);
            }
        }


        //// Routes
        {
            //// Larkspur-Ferry-Bldg route Drawing
            UIBezierPath* larkspurFerryBldgRoutePath = UIBezierPath.bezierPath;
            [larkspurFerryBldgRoutePath moveToPoint: CGPointMake(-301.83, -1219.67)];
            [larkspurFerryBldgRoutePath addLineToPoint: CGPointMake(866.83, -50.03)];
            [larkspurFerryBldgRoutePath addLineToPoint: CGPointMake(866.83, 597.33)];
            larkspurFerryBldgRoutePath.miterLimit = 4;

            [FerryLifeStyleKit.disabled setStroke];
            larkspurFerryBldgRoutePath.lineWidth = 26;
            [larkspurFerryBldgRoutePath stroke];


            //// Sausalito-Ferry-Bldg route Drawing
            UIBezierPath* sausalitoFerryBldgRoutePath = UIBezierPath.bezierPath;
            [sausalitoFerryBldgRoutePath moveToPoint: CGPointMake(829.56, 578.68)];
            [sausalitoFerryBldgRoutePath addLineToPoint: CGPointMake(829.56, 305.47)];
            [sausalitoFerryBldgRoutePath addLineToPoint: CGPointMake(329.64, -194.86)];
            [sausalitoFerryBldgRoutePath addLineToPoint: CGPointMake(-88.05, -194.86)];
            sausalitoFerryBldgRoutePath.miterLimit = 4;

            [FerryLifeStyleKit.disabled setStroke];
            sausalitoFerryBldgRoutePath.lineWidth = 26;
            [sausalitoFerryBldgRoutePath stroke];


            //// Sausalito-Pier-41 route Drawing
            UIBezierPath* sausalitoPier41RoutePath = UIBezierPath.bezierPath;
            [sausalitoPier41RoutePath moveToPoint: CGPointMake(-91.34, -158.65)];
            [sausalitoPier41RoutePath addLineToPoint: CGPointMake(207.95, -158.65)];
            [sausalitoPier41RoutePath addLineToPoint: CGPointMake(531.91, 165.58)];
            [sausalitoPier41RoutePath addLineToPoint: CGPointMake(531.91, 447.02)];
            sausalitoPier41RoutePath.miterLimit = 4;

            [FerryLifeStyleKit.disabled setStroke];
            sausalitoPier41RoutePath.lineWidth = 26;
            [sausalitoPier41RoutePath stroke];


            //// Tiburon-Ferry-Bldg route Drawing
            UIBezierPath* tiburonFerryBldgRoutePath = UIBezierPath.bezierPath;
            [tiburonFerryBldgRoutePath moveToPoint: CGPointMake(198.09, -273.86)];
            [tiburonFerryBldgRoutePath addLineToPoint: CGPointMake(793.38, 321.93)];
            [tiburonFerryBldgRoutePath addLineToPoint: CGPointMake(793.38, 588.56)];
            tiburonFerryBldgRoutePath.miterLimit = 4;

            [FerryLifeStyleKit.dark setStroke];
            tiburonFerryBldgRoutePath.lineWidth = 26;
            [tiburonFerryBldgRoutePath stroke];


            //// Tiburon-Pier-41 route Drawing
            UIBezierPath* tiburonPier41RoutePath = UIBezierPath.bezierPath;
            [tiburonPier41RoutePath moveToPoint: CGPointMake(171.77, -247.53)];
            [tiburonPier41RoutePath addLineToPoint: CGPointMake(568.09, 149.12)];
            [tiburonPier41RoutePath addLineToPoint: CGPointMake(568.09, 450.31)];
            tiburonPier41RoutePath.miterLimit = 4;

            [FerryLifeStyleKit.dark setStroke];
            tiburonPier41RoutePath.lineWidth = 26;
            [tiburonPier41RoutePath stroke];
        }


        //// Terminals
        {
            //// Pier 41 marker Drawing
            CGRect pier41MarkerRect = CGRectMake(404, 383, 287, 292);
            CGContextSaveGState(context);
            UIRectClip(pier41MarkerRect);
            CGContextTranslateCTM(context, pier41MarkerRect.origin.x, pier41MarkerRect.origin.y);
            CGContextScaleCTM(context, pier41MarkerRect.size.width / 44, pier41MarkerRect.size.height / 44);

            [FerryLifeStyleKit drawTerminalMarkerWithScalePercent: 100];
            CGContextRestoreGState(context);


            //// Pier 41 label Drawing
            CGRect pier41LabelRect = CGRectMake(35, 474, 405, 192);
            {
                NSString* textContent = @"Pier 41";
                NSMutableParagraphStyle* pier41LabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
                pier41LabelStyle.alignment = NSTextAlignmentRight;

                NSDictionary* pier41LabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: 100], NSForegroundColorAttributeName: FerryLifeStyleKit.dark, NSParagraphStyleAttributeName: pier41LabelStyle};

                CGFloat pier41LabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(pier41LabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: pier41LabelFontAttributes context: nil].size.height;
                CGContextSaveGState(context);
                CGContextClipToRect(context, pier41LabelRect);
                [textContent drawInRect: CGRectMake(CGRectGetMinX(pier41LabelRect), CGRectGetMinY(pier41LabelRect) + (CGRectGetHeight(pier41LabelRect) - pier41LabelTextHeight) / 2, CGRectGetWidth(pier41LabelRect), pier41LabelTextHeight) withAttributes: pier41LabelFontAttributes];
                CGContextRestoreGState(context);
            }


            //// Ferry Bldg marker Drawing
            CGRect ferryBldgMarkerRect = CGRectMake(684, 523, 290, 290);
            CGContextSaveGState(context);
            UIRectClip(ferryBldgMarkerRect);
            CGContextTranslateCTM(context, ferryBldgMarkerRect.origin.x, ferryBldgMarkerRect.origin.y);
            CGContextScaleCTM(context, ferryBldgMarkerRect.size.width / 44, ferryBldgMarkerRect.size.height / 44);

            [FerryLifeStyleKit drawTerminalMarkerWithScalePercent: 100];
            CGContextRestoreGState(context);


            //// Ferry Bldg label Drawing
            CGRect ferryBldgLabelRect = CGRectMake(172, 609, 551, 191);
            {
                NSString* textContent = @"Ferry Bldg";
                NSMutableParagraphStyle* ferryBldgLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
                ferryBldgLabelStyle.alignment = NSTextAlignmentRight;

                NSDictionary* ferryBldgLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: 100], NSForegroundColorAttributeName: FerryLifeStyleKit.dark, NSParagraphStyleAttributeName: ferryBldgLabelStyle};

                CGFloat ferryBldgLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(ferryBldgLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: ferryBldgLabelFontAttributes context: nil].size.height;
                CGContextSaveGState(context);
                CGContextClipToRect(context, ferryBldgLabelRect);
                [textContent drawInRect: CGRectMake(CGRectGetMinX(ferryBldgLabelRect), CGRectGetMinY(ferryBldgLabelRect) + (CGRectGetHeight(ferryBldgLabelRect) - ferryBldgLabelTextHeight) / 2, CGRectGetWidth(ferryBldgLabelRect), ferryBldgLabelTextHeight) withAttributes: ferryBldgLabelFontAttributes];
                CGContextRestoreGState(context);
            }
        }
    }
}

#pragma mark Generated Images

+ (UIImage*)imageOfTerminalMarkerWithScalePercent: (CGFloat)scalePercent
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(44, 44), NO, 0.0f);
    [FerryLifeStyleKit drawTerminalMarkerWithScalePercent: scalePercent];

    UIImage* imageOfTerminalMarker = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfTerminalMarker;
}

+ (UIImage*)imageOfDisabledTerminalMarkerWithScalePercent: (CGFloat)scalePercent
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(44, 44), NO, 0.0f);
    [FerryLifeStyleKit drawDisabledTerminalMarkerWithScalePercent: scalePercent];

    UIImage* imageOfDisabledTerminalMarker = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfDisabledTerminalMarker;
}

+ (UIImage*)imageOfHiddenTerminalMarker
{
    if (_imageOfHiddenTerminalMarker)
        return _imageOfHiddenTerminalMarker;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(44, 44), NO, 0.0f);
    [FerryLifeStyleKit drawHiddenTerminalMarker];

    _imageOfHiddenTerminalMarker = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfHiddenTerminalMarker;
}

+ (UIImage*)imageOfSelectedTerminalMarkerWithScalePercent: (CGFloat)scalePercent
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(44, 44), NO, 0.0f);
    [FerryLifeStyleKit drawSelectedTerminalMarkerWithScalePercent: scalePercent];

    UIImage* imageOfSelectedTerminalMarker = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfSelectedTerminalMarker;
}

#pragma mark Customization Infrastructure

- (void)setHiddenTerminalMarkerTargets: (NSArray*)hiddenTerminalMarkerTargets
{
    _hiddenTerminalMarkerTargets = hiddenTerminalMarkerTargets;

    for (id target in self.hiddenTerminalMarkerTargets)
        [target setImage: FerryLifeStyleKit.imageOfHiddenTerminalMarker];
}


@end
