//
//  FerryLifeStyleKit.m
//  Build with Reactive Native
//
//  Created by Mars on 2015-05-12.
//  Copyright (c) 2015 Mars Hall. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "FerryLifeStyleKit.h"


@implementation FerryLifeStyleKit

#pragma mark Cache

static UIColor* _water = nil;
static UIColor* _land = nil;
static UIColor* _bright = nil;
static UIColor* _dark = nil;
static UIColor* _vividWater = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _water = [UIColor colorWithRed: 0.447 green: 0.69 blue: 0.682 alpha: 1];
    CGFloat waterHSBA[4];
    [_water getHue: &waterHSBA[0] saturation: &waterHSBA[1] brightness: &waterHSBA[2] alpha: &waterHSBA[3]];

    _vividWater = [UIColor colorWithHue: waterHSBA[0] saturation: 0.6 brightness: waterHSBA[2] alpha: waterHSBA[3]];
    _land = [UIColor colorWithRed: 0.675 green: 0.741 blue: 0.741 alpha: 1];
    _bright = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    _dark = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)water { return _water; }
+ (UIColor*)land { return _land; }
+ (UIColor*)bright { return _bright; }
+ (UIColor*)dark { return _dark; }
+ (UIColor*)vividWater { return _vividWater; }

#pragma mark Drawing Methods

+ (void)drawFerryMap
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Map
    {
        //// Richmond Drawing
        UIBezierPath* richmondPath = UIBezierPath.bezierPath;
        [richmondPath moveToPoint: CGPointMake(198.33, 8.83)];
        [richmondPath addLineToPoint: CGPointMake(207, 13.5)];
        [richmondPath addLineToPoint: CGPointMake(208.33, 23.5)];
        [richmondPath addLineToPoint: CGPointMake(207, 30.83)];
        [richmondPath addLineToPoint: CGPointMake(217.67, 32.17)];
        [richmondPath addLineToPoint: CGPointMake(222.33, 37.5)];
        [richmondPath addLineToPoint: CGPointMake(223, 54.83)];
        [richmondPath addLineToPoint: CGPointMake(233.67, 64.17)];
        [richmondPath addLineToPoint: CGPointMake(247.67, 66.83)];
        [richmondPath addLineToPoint: CGPointMake(260.33, 86.83)];
        [richmondPath addLineToPoint: CGPointMake(257, 106.17)];
        [richmondPath addLineToPoint: CGPointMake(266.33, 109.5)];
        [richmondPath addLineToPoint: CGPointMake(270.33, 104.83)];
        [richmondPath addLineToPoint: CGPointMake(277, 108.83)];
        [richmondPath addLineToPoint: CGPointMake(293.67, 114.83)];
        [richmondPath addLineToPoint: CGPointMake(302.33, 112.17)];
        [richmondPath addLineToPoint: CGPointMake(310.33, 108.83)];
        [richmondPath addLineToPoint: CGPointMake(323.67, 108.83)];
        [richmondPath addLineToPoint: CGPointMake(324.67, 108.83)];
        [richmondPath addLineToPoint: CGPointMake(324.67, 5.5)];
        [richmondPath addLineToPoint: CGPointMake(198.33, 5.5)];
        [richmondPath addLineToPoint: CGPointMake(198.33, 8.83)];
        [richmondPath closePath];
        richmondPath.miterLimit = 4;

        [FerryLifeStyleKit.land setFill];
        [richmondPath fill];


        //// Marin Drawing
        UIBezierPath* marinPath = UIBezierPath.bezierPath;
        [marinPath moveToPoint: CGPointMake(19, 273.5)];
        [marinPath addLineToPoint: CGPointMake(25.67, 297.5)];
        [marinPath addLineToPoint: CGPointMake(31.67, 288.17)];
        [marinPath addLineToPoint: CGPointMake(44.33, 282.17)];
        [marinPath addLineToPoint: CGPointMake(63.67, 284.5)];
        [marinPath addLineToPoint: CGPointMake(79.17, 286.5)];
        [marinPath addLineToPoint: CGPointMake(92.67, 278)];
        [marinPath addLineToPoint: CGPointMake(108.17, 278)];
        [marinPath addLineToPoint: CGPointMake(114.67, 266.5)];
        [marinPath addLineToPoint: CGPointMake(122.17, 263.5)];
        [marinPath addLineToPoint: CGPointMake(118.67, 250.5)];
        [marinPath addLineToPoint: CGPointMake(113.17, 231.5)];
        [marinPath addLineToPoint: CGPointMake(113.17, 222.5)];
        [marinPath addLineToPoint: CGPointMake(112.67, 216)];
        [marinPath addLineToPoint: CGPointMake(100.67, 202.5)];
        [marinPath addLineToPoint: CGPointMake(86.17, 191)];
        [marinPath addLineToPoint: CGPointMake(71.17, 182.5)];
        [marinPath addLineToPoint: CGPointMake(59.67, 172)];
        [marinPath addLineToPoint: CGPointMake(43.17, 159.5)];
        [marinPath addLineToPoint: CGPointMake(39.17, 150)];
        [marinPath addLineToPoint: CGPointMake(37.67, 139)];
        [marinPath addLineToPoint: CGPointMake(43.67, 144)];
        [marinPath addLineToPoint: CGPointMake(56.67, 154.5)];
        [marinPath addLineToPoint: CGPointMake(80.17, 174.5)];
        [marinPath addLineToPoint: CGPointMake(83.17, 171)];
        [marinPath addLineToPoint: CGPointMake(73.67, 154)];
        [marinPath addLineToPoint: CGPointMake(72.17, 140)];
        [marinPath addLineToPoint: CGPointMake(94.17, 137.5)];
        [marinPath addLineToPoint: CGPointMake(104.17, 147.5)];
        [marinPath addLineToPoint: CGPointMake(123.17, 157.5)];
        [marinPath addLineToPoint: CGPointMake(150.17, 185)];
        [marinPath addLineToPoint: CGPointMake(167.67, 176)];
        [marinPath addLineToPoint: CGPointMake(167.67, 169.5)];
        [marinPath addLineToPoint: CGPointMake(172.17, 167.5)];
        [marinPath addLineToPoint: CGPointMake(177.67, 163.5)];
        [marinPath addLineToPoint: CGPointMake(166.67, 150)];
        [marinPath addLineToPoint: CGPointMake(160.67, 141.5)];
        [marinPath addLineToPoint: CGPointMake(147.67, 138)];
        [marinPath addLineToPoint: CGPointMake(115.67, 120.5)];
        [marinPath addLineToPoint: CGPointMake(117.17, 110.5)];
        [marinPath addLineToPoint: CGPointMake(113.67, 98)];
        [marinPath addLineToPoint: CGPointMake(101.67, 87)];
        [marinPath addLineToPoint: CGPointMake(83.17, 81)];
        [marinPath addLineToPoint: CGPointMake(70.67, 65.5)];
        [marinPath addLineToPoint: CGPointMake(67.17, 36.5)];
        [marinPath addLineToPoint: CGPointMake(94.17, 50)];
        [marinPath addLineToPoint: CGPointMake(105.17, 45.5)];
        [marinPath addLineToPoint: CGPointMake(92.82, 5.5)];
        [marinPath addLineToPoint: CGPointMake(0, 5.5)];
        [marinPath addLineToPoint: CGPointMake(0, 264.3)];
        [marinPath addLineToPoint: CGPointMake(13, 269.5)];
        [marinPath addLineToPoint: CGPointMake(19, 273.5)];
        [marinPath closePath];
        marinPath.miterLimit = 4;

        [FerryLifeStyleKit.land setFill];
        [marinPath fill];


        //// San Francisco Drawing
        UIBezierPath* sanFranciscoPath = UIBezierPath.bezierPath;
        [sanFranciscoPath moveToPoint: CGPointMake(262.33, 375.5)];
        [sanFranciscoPath addLineToPoint: CGPointMake(261.67, 364.83)];
        [sanFranciscoPath addLineToPoint: CGPointMake(259.67, 355.5)];
        [sanFranciscoPath addLineToPoint: CGPointMake(257, 346.17)];
        [sanFranciscoPath addLineToPoint: CGPointMake(251.67, 335.5)];
        [sanFranciscoPath addLineToPoint: CGPointMake(240.33, 325.5)];
        [sanFranciscoPath addLineToPoint: CGPointMake(235, 319.5)];
        [sanFranciscoPath addLineToPoint: CGPointMake(228.33, 314.83)];
        [sanFranciscoPath addLineToPoint: CGPointMake(213, 312.83)];
        [sanFranciscoPath addLineToPoint: CGPointMake(195, 317.5)];
        [sanFranciscoPath addLineToPoint: CGPointMake(182.33, 319.5)];
        [sanFranciscoPath addLineToPoint: CGPointMake(165.67, 316.83)];
        [sanFranciscoPath addLineToPoint: CGPointMake(150.33, 322.17)];
        [sanFranciscoPath addLineToPoint: CGPointMake(134.33, 322.83)];
        [sanFranciscoPath addLineToPoint: CGPointMake(128.33, 318.17)];
        [sanFranciscoPath addLineToPoint: CGPointMake(119.67, 313.5)];
        [sanFranciscoPath addLineToPoint: CGPointMake(113, 320.83)];
        [sanFranciscoPath addLineToPoint: CGPointMake(99, 356.83)];
        [sanFranciscoPath addLineToPoint: CGPointMake(81, 359.5)];
        [sanFranciscoPath addLineToPoint: CGPointMake(63.67, 361.5)];
        [sanFranciscoPath addLineToPoint: CGPointMake(55.67, 364.83)];
        [sanFranciscoPath addLineToPoint: CGPointMake(53, 372.83)];
        [sanFranciscoPath addLineToPoint: CGPointMake(57, 378.83)];
        [sanFranciscoPath addLineToPoint: CGPointMake(58.16, 390.83)];
        [sanFranciscoPath addLineToPoint: CGPointMake(264.56, 390.83)];
        [sanFranciscoPath addLineToPoint: CGPointMake(262.33, 385.5)];
        [sanFranciscoPath addLineToPoint: CGPointMake(262.33, 375.5)];
        [sanFranciscoPath closePath];
        sanFranciscoPath.miterLimit = 4;

        [FerryLifeStyleKit.land setFill];
        [sanFranciscoPath fill];


        //// Bay Waters Drawing
        UIBezierPath* bayWatersPath = UIBezierPath.bezierPath;
        [bayWatersPath moveToPoint: CGPointMake(58.16, 390.83)];
        [bayWatersPath addLineToPoint: CGPointMake(57, 378.83)];
        [bayWatersPath addLineToPoint: CGPointMake(53, 372.83)];
        [bayWatersPath addLineToPoint: CGPointMake(55.67, 364.83)];
        [bayWatersPath addLineToPoint: CGPointMake(63.67, 361.5)];
        [bayWatersPath addLineToPoint: CGPointMake(81, 359.5)];
        [bayWatersPath addLineToPoint: CGPointMake(99, 356.83)];
        [bayWatersPath addLineToPoint: CGPointMake(113, 320.83)];
        [bayWatersPath addLineToPoint: CGPointMake(119.67, 313.5)];
        [bayWatersPath addLineToPoint: CGPointMake(128.33, 318.17)];
        [bayWatersPath addLineToPoint: CGPointMake(134.33, 322.83)];
        [bayWatersPath addLineToPoint: CGPointMake(150.33, 322.17)];
        [bayWatersPath addLineToPoint: CGPointMake(165.67, 316.83)];
        [bayWatersPath addLineToPoint: CGPointMake(182.33, 319.5)];
        [bayWatersPath addLineToPoint: CGPointMake(195, 317.5)];
        [bayWatersPath addLineToPoint: CGPointMake(213, 312.83)];
        [bayWatersPath addLineToPoint: CGPointMake(228.33, 314.83)];
        [bayWatersPath addLineToPoint: CGPointMake(235, 319.5)];
        [bayWatersPath addLineToPoint: CGPointMake(240.33, 325.5)];
        [bayWatersPath addLineToPoint: CGPointMake(251.67, 335.5)];
        [bayWatersPath addLineToPoint: CGPointMake(257, 346.17)];
        [bayWatersPath addLineToPoint: CGPointMake(259.67, 355.5)];
        [bayWatersPath addLineToPoint: CGPointMake(261.67, 364.83)];
        [bayWatersPath addLineToPoint: CGPointMake(262.33, 375.5)];
        [bayWatersPath addLineToPoint: CGPointMake(262.33, 385.5)];
        [bayWatersPath addLineToPoint: CGPointMake(264.56, 390.83)];
        [bayWatersPath addLineToPoint: CGPointMake(265.67, 393.5)];
        [bayWatersPath addLineToPoint: CGPointMake(324.67, 393.5)];
        [bayWatersPath addLineToPoint: CGPointMake(324.67, 108.83)];
        [bayWatersPath addLineToPoint: CGPointMake(323.67, 108.83)];
        [bayWatersPath addLineToPoint: CGPointMake(310.33, 108.83)];
        [bayWatersPath addLineToPoint: CGPointMake(302.33, 112.17)];
        [bayWatersPath addLineToPoint: CGPointMake(293.67, 114.83)];
        [bayWatersPath addLineToPoint: CGPointMake(277, 108.83)];
        [bayWatersPath addLineToPoint: CGPointMake(270.33, 104.83)];
        [bayWatersPath addLineToPoint: CGPointMake(266.33, 109.5)];
        [bayWatersPath addLineToPoint: CGPointMake(257, 106.17)];
        [bayWatersPath addLineToPoint: CGPointMake(260.33, 86.83)];
        [bayWatersPath addLineToPoint: CGPointMake(247.67, 66.83)];
        [bayWatersPath addLineToPoint: CGPointMake(233.67, 64.17)];
        [bayWatersPath addLineToPoint: CGPointMake(223, 54.83)];
        [bayWatersPath addLineToPoint: CGPointMake(222.33, 37.5)];
        [bayWatersPath addLineToPoint: CGPointMake(217.67, 32.17)];
        [bayWatersPath addLineToPoint: CGPointMake(207, 30.83)];
        [bayWatersPath addLineToPoint: CGPointMake(208.33, 23.5)];
        [bayWatersPath addLineToPoint: CGPointMake(207, 13.5)];
        [bayWatersPath addLineToPoint: CGPointMake(198.33, 8.83)];
        [bayWatersPath addLineToPoint: CGPointMake(198.33, 5.5)];
        [bayWatersPath addLineToPoint: CGPointMake(198.33, 2.17)];
        [bayWatersPath addLineToPoint: CGPointMake(92.67, 5)];
        [bayWatersPath addLineToPoint: CGPointMake(92.82, 5.5)];
        [bayWatersPath addLineToPoint: CGPointMake(105.17, 45.5)];
        [bayWatersPath addLineToPoint: CGPointMake(94.17, 50)];
        [bayWatersPath addLineToPoint: CGPointMake(67.17, 36.5)];
        [bayWatersPath addLineToPoint: CGPointMake(70.67, 65.5)];
        [bayWatersPath addLineToPoint: CGPointMake(83.17, 81)];
        [bayWatersPath addLineToPoint: CGPointMake(101.67, 87)];
        [bayWatersPath addLineToPoint: CGPointMake(113.67, 98)];
        [bayWatersPath addLineToPoint: CGPointMake(117.17, 110.5)];
        [bayWatersPath addLineToPoint: CGPointMake(115.67, 120.5)];
        [bayWatersPath addLineToPoint: CGPointMake(147.67, 138)];
        [bayWatersPath addLineToPoint: CGPointMake(160.67, 141.5)];
        [bayWatersPath addLineToPoint: CGPointMake(166.67, 150)];
        [bayWatersPath addLineToPoint: CGPointMake(177.67, 163.5)];
        [bayWatersPath addLineToPoint: CGPointMake(172.17, 167.5)];
        [bayWatersPath addLineToPoint: CGPointMake(167.67, 169.5)];
        [bayWatersPath addLineToPoint: CGPointMake(167.67, 176)];
        [bayWatersPath addLineToPoint: CGPointMake(150.17, 185)];
        [bayWatersPath addLineToPoint: CGPointMake(123.17, 157.5)];
        [bayWatersPath addLineToPoint: CGPointMake(104.17, 147.5)];
        [bayWatersPath addLineToPoint: CGPointMake(94.17, 137.5)];
        [bayWatersPath addLineToPoint: CGPointMake(72.17, 140)];
        [bayWatersPath addLineToPoint: CGPointMake(73.67, 154)];
        [bayWatersPath addLineToPoint: CGPointMake(83.17, 171)];
        [bayWatersPath addLineToPoint: CGPointMake(80.17, 174.5)];
        [bayWatersPath addLineToPoint: CGPointMake(56.67, 154.5)];
        [bayWatersPath addLineToPoint: CGPointMake(43.67, 144)];
        [bayWatersPath addLineToPoint: CGPointMake(37.67, 139)];
        [bayWatersPath addLineToPoint: CGPointMake(39.17, 150)];
        [bayWatersPath addLineToPoint: CGPointMake(43.17, 159.5)];
        [bayWatersPath addLineToPoint: CGPointMake(59.67, 172)];
        [bayWatersPath addLineToPoint: CGPointMake(71.17, 182.5)];
        [bayWatersPath addLineToPoint: CGPointMake(86.17, 191)];
        [bayWatersPath addLineToPoint: CGPointMake(100.67, 202.5)];
        [bayWatersPath addLineToPoint: CGPointMake(112.67, 216)];
        [bayWatersPath addLineToPoint: CGPointMake(113.17, 222.5)];
        [bayWatersPath addLineToPoint: CGPointMake(113.17, 231.5)];
        [bayWatersPath addLineToPoint: CGPointMake(118.67, 250.5)];
        [bayWatersPath addLineToPoint: CGPointMake(122.17, 263.5)];
        [bayWatersPath addLineToPoint: CGPointMake(114.67, 266.5)];
        [bayWatersPath addLineToPoint: CGPointMake(108.17, 278)];
        [bayWatersPath addLineToPoint: CGPointMake(92.67, 278)];
        [bayWatersPath addLineToPoint: CGPointMake(79.17, 286.5)];
        [bayWatersPath addLineToPoint: CGPointMake(63.67, 284.5)];
        [bayWatersPath addLineToPoint: CGPointMake(44.33, 282.17)];
        [bayWatersPath addLineToPoint: CGPointMake(31.67, 288.17)];
        [bayWatersPath addLineToPoint: CGPointMake(25.67, 297.5)];
        [bayWatersPath addLineToPoint: CGPointMake(19, 273.5)];
        [bayWatersPath addLineToPoint: CGPointMake(13, 269.5)];
        [bayWatersPath addLineToPoint: CGPointMake(0, 264.3)];
        [bayWatersPath addLineToPoint: CGPointMake(0, 399.5)];
        [bayWatersPath addLineToPoint: CGPointMake(59, 399.5)];
        [bayWatersPath addLineToPoint: CGPointMake(58.16, 390.83)];
        [bayWatersPath closePath];
        bayWatersPath.miterLimit = 4;

        [FerryLifeStyleKit.water setFill];
        [bayWatersPath fill];


        //// SF Bay label Drawing
        CGRect sFBayLabelRect = CGRectMake(208, 126, 107, 36);
        {
            NSString* textContent = @"San Franscisco Bay";
            NSMutableParagraphStyle* sFBayLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
            sFBayLabelStyle.alignment = NSTextAlignmentCenter;

            NSDictionary* sFBayLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.bright, NSParagraphStyleAttributeName: sFBayLabelStyle};

            CGFloat sFBayLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(sFBayLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: sFBayLabelFontAttributes context: nil].size.height;
            CGContextSaveGState(context);
            CGContextClipToRect(context, sFBayLabelRect);
            [textContent drawInRect: CGRectMake(CGRectGetMinX(sFBayLabelRect), CGRectGetMinY(sFBayLabelRect) + (CGRectGetHeight(sFBayLabelRect) - sFBayLabelTextHeight) / 2, CGRectGetWidth(sFBayLabelRect), sFBayLabelTextHeight) withAttributes: sFBayLabelFontAttributes];
            CGContextRestoreGState(context);
        }


        //// Pacific Ocean label Drawing
        CGRect pacificOceanLabelRect = CGRectMake(0, 313, 107, 36);
        {
            NSString* textContent = @"Pacific Ocean";
            NSMutableParagraphStyle* pacificOceanLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
            pacificOceanLabelStyle.alignment = NSTextAlignmentCenter;

            NSDictionary* pacificOceanLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.bright, NSParagraphStyleAttributeName: pacificOceanLabelStyle};

            CGFloat pacificOceanLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(pacificOceanLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: pacificOceanLabelFontAttributes context: nil].size.height;
            CGContextSaveGState(context);
            CGContextClipToRect(context, pacificOceanLabelRect);
            [textContent drawInRect: CGRectMake(CGRectGetMinX(pacificOceanLabelRect), CGRectGetMinY(pacificOceanLabelRect) + (CGRectGetHeight(pacificOceanLabelRect) - pacificOceanLabelTextHeight) / 2, CGRectGetWidth(pacificOceanLabelRect), pacificOceanLabelTextHeight) withAttributes: pacificOceanLabelFontAttributes];
            CGContextRestoreGState(context);
        }


        //// San Francisco label Drawing
        CGRect sanFranciscoLabelRect = CGRectMake(109, 355, 107, 36);
        {
            NSString* textContent = @"San Francisco";
            NSMutableParagraphStyle* sanFranciscoLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
            sanFranciscoLabelStyle.alignment = NSTextAlignmentCenter;

            NSDictionary* sanFranciscoLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.bright, NSParagraphStyleAttributeName: sanFranciscoLabelStyle};

            CGFloat sanFranciscoLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(sanFranciscoLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: sanFranciscoLabelFontAttributes context: nil].size.height;
            CGContextSaveGState(context);
            CGContextClipToRect(context, sanFranciscoLabelRect);
            [textContent drawInRect: CGRectMake(CGRectGetMinX(sanFranciscoLabelRect), CGRectGetMinY(sanFranciscoLabelRect) + (CGRectGetHeight(sanFranciscoLabelRect) - sanFranciscoLabelTextHeight) / 2, CGRectGetWidth(sanFranciscoLabelRect), sanFranciscoLabelTextHeight) withAttributes: sanFranciscoLabelFontAttributes];
            CGContextRestoreGState(context);
        }


        //// Marin label Drawing
        CGRect marinLabelRect = CGRectMake(0, 90, 107, 36);
        {
            NSString* textContent = @"Marin";
            NSMutableParagraphStyle* marinLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
            marinLabelStyle.alignment = NSTextAlignmentCenter;

            NSDictionary* marinLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.bright, NSParagraphStyleAttributeName: marinLabelStyle};

            CGFloat marinLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(marinLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: marinLabelFontAttributes context: nil].size.height;
            CGContextSaveGState(context);
            CGContextClipToRect(context, marinLabelRect);
            [textContent drawInRect: CGRectMake(CGRectGetMinX(marinLabelRect), CGRectGetMinY(marinLabelRect) + (CGRectGetHeight(marinLabelRect) - marinLabelTextHeight) / 2, CGRectGetWidth(marinLabelRect), marinLabelTextHeight) withAttributes: marinLabelFontAttributes];
            CGContextRestoreGState(context);
        }
    }


    //// Routes
    {
        //// Larkspur marker Drawing
        UIBezierPath* larkspurMarkerPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(58.67, 25.5, 25, 25)];
        [FerryLifeStyleKit.bright setFill];
        [larkspurMarkerPath fill];
        [FerryLifeStyleKit.dark setStroke];
        larkspurMarkerPath.lineWidth = 4;
        [larkspurMarkerPath stroke];


        //// Tiburon marker Drawing
        UIBezierPath* tiburonMarkerPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(134.17, 170, 25, 25)];
        [FerryLifeStyleKit.bright setFill];
        [tiburonMarkerPath fill];
        [FerryLifeStyleKit.dark setStroke];
        tiburonMarkerPath.lineWidth = 4;
        [tiburonMarkerPath stroke];


        //// Sausalito marker Drawing
        UIBezierPath* sausalitoMarkerPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(88.67, 190.5, 25, 25)];
        [FerryLifeStyleKit.bright setFill];
        [sausalitoMarkerPath fill];
        [FerryLifeStyleKit.dark setStroke];
        sausalitoMarkerPath.lineWidth = 4;
        [sausalitoMarkerPath stroke];


        //// Pier 41 marker Drawing
        UIBezierPath* pier41MarkerPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(198.67, 299.5, 25, 25)];
        [FerryLifeStyleKit.bright setFill];
        [pier41MarkerPath fill];
        [FerryLifeStyleKit.dark setStroke];
        pier41MarkerPath.lineWidth = 4;
        [pier41MarkerPath stroke];


        //// Ferry Bldg marker Drawing
        UIBezierPath* ferryBldgMarkerPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(241.17, 320.5, 25, 25)];
        [FerryLifeStyleKit.bright setFill];
        [ferryBldgMarkerPath fill];
        [FerryLifeStyleKit.dark setStroke];
        ferryBldgMarkerPath.lineWidth = 4;
        [ferryBldgMarkerPath stroke];


        //// Larkspur-Ferry-Bldg route Drawing
        UIBezierPath* larkspurFerryBldgRoutePath = UIBezierPath.bezierPath;
        [larkspurFerryBldgRoutePath moveToPoint: CGPointMake(81.17, 47.33)];
        [larkspurFerryBldgRoutePath addLineToPoint: CGPointMake(258.83, 225)];
        [larkspurFerryBldgRoutePath addLineToPoint: CGPointMake(258.83, 323.33)];
        larkspurFerryBldgRoutePath.miterLimit = 4;

        [FerryLifeStyleKit.dark setStroke];
        larkspurFerryBldgRoutePath.lineWidth = 4;
        [larkspurFerryBldgRoutePath stroke];


        //// Tiburon-Ferry-Bldg route Drawing
        UIBezierPath* tiburonFerryBldgRoutePath = UIBezierPath.bezierPath;
        [tiburonFerryBldgRoutePath moveToPoint: CGPointMake(157.17, 191)];
        [tiburonFerryBldgRoutePath addLineToPoint: CGPointMake(247.67, 281.5)];
        [tiburonFerryBldgRoutePath addLineToPoint: CGPointMake(247.67, 322)];
        tiburonFerryBldgRoutePath.miterLimit = 4;

        [FerryLifeStyleKit.dark setStroke];
        tiburonFerryBldgRoutePath.lineWidth = 4;
        [tiburonFerryBldgRoutePath stroke];


        //// Tiburon-Pier-41 route Drawing
        UIBezierPath* tiburonPier41RoutePath = UIBezierPath.bezierPath;
        [tiburonPier41RoutePath moveToPoint: CGPointMake(153.17, 195)];
        [tiburonPier41RoutePath addLineToPoint: CGPointMake(213.42, 255.25)];
        [tiburonPier41RoutePath addLineToPoint: CGPointMake(213.42, 301)];
        tiburonPier41RoutePath.miterLimit = 4;

        [FerryLifeStyleKit.dark setStroke];
        tiburonPier41RoutePath.lineWidth = 4;
        [tiburonPier41RoutePath stroke];


        //// Sausalito-Ferry-Bldg route Drawing
        UIBezierPath* sausalitoFerryBldgRoutePath = UIBezierPath.bezierPath;
        [sausalitoFerryBldgRoutePath moveToPoint: CGPointMake(253.17, 320.5)];
        [sausalitoFerryBldgRoutePath addLineToPoint: CGPointMake(253.17, 279)];
        [sausalitoFerryBldgRoutePath addLineToPoint: CGPointMake(177.17, 203)];
        [sausalitoFerryBldgRoutePath addLineToPoint: CGPointMake(113.67, 203)];
        sausalitoFerryBldgRoutePath.miterLimit = 4;

        [FerryLifeStyleKit.dark setStroke];
        sausalitoFerryBldgRoutePath.lineWidth = 4;
        [sausalitoFerryBldgRoutePath stroke];


        //// Sausalito-Pier-41 route Drawing
        UIBezierPath* sausalitoPier41RoutePath = UIBezierPath.bezierPath;
        [sausalitoPier41RoutePath moveToPoint: CGPointMake(113.17, 208.5)];
        [sausalitoPier41RoutePath addLineToPoint: CGPointMake(158.67, 208.5)];
        [sausalitoPier41RoutePath addLineToPoint: CGPointMake(207.92, 257.75)];
        [sausalitoPier41RoutePath addLineToPoint: CGPointMake(207.92, 300.5)];
        sausalitoPier41RoutePath.miterLimit = 4;

        [FerryLifeStyleKit.dark setStroke];
        sausalitoPier41RoutePath.lineWidth = 4;
        [sausalitoPier41RoutePath stroke];


        //// Sausalito-Tiburon route Drawing
        UIBezierPath* sausalitoTiburonRoutePath = UIBezierPath.bezierPath;
        [sausalitoTiburonRoutePath moveToPoint: CGPointMake(113.67, 197.5)];
        [sausalitoTiburonRoutePath addLineToPoint: CGPointMake(131.17, 197.5)];
        [sausalitoTiburonRoutePath addLineToPoint: CGPointMake(137.42, 191.25)];
        sausalitoTiburonRoutePath.miterLimit = 4;

        [FerryLifeStyleKit.dark setStroke];
        sausalitoTiburonRoutePath.lineWidth = 4;
        [sausalitoTiburonRoutePath stroke];
    }


    //// Terminals
    {
        //// Larkspur label Drawing
        CGRect larkspurLabelRect = CGRectMake(2, 18, 51, 29);
        {
            NSString* textContent = @"Larkspur";
            NSMutableParagraphStyle* larkspurLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
            larkspurLabelStyle.alignment = NSTextAlignmentRight;

            NSDictionary* larkspurLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.dark, NSParagraphStyleAttributeName: larkspurLabelStyle};

            CGFloat larkspurLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(larkspurLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: larkspurLabelFontAttributes context: nil].size.height;
            CGContextSaveGState(context);
            CGContextClipToRect(context, larkspurLabelRect);
            [textContent drawInRect: CGRectMake(CGRectGetMinX(larkspurLabelRect), CGRectGetMinY(larkspurLabelRect) + (CGRectGetHeight(larkspurLabelRect) - larkspurLabelTextHeight) / 2, CGRectGetWidth(larkspurLabelRect), larkspurLabelTextHeight) withAttributes: larkspurLabelFontAttributes];
            CGContextRestoreGState(context);
        }


        //// Sausalito label Drawing
        CGRect sausalitoLabelRect = CGRectMake(33, 186, 51, 29);
        {
            NSString* textContent = @"Sausalito";
            NSMutableParagraphStyle* sausalitoLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
            sausalitoLabelStyle.alignment = NSTextAlignmentRight;

            NSDictionary* sausalitoLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.dark, NSParagraphStyleAttributeName: sausalitoLabelStyle};

            CGFloat sausalitoLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(sausalitoLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: sausalitoLabelFontAttributes context: nil].size.height;
            CGContextSaveGState(context);
            CGContextClipToRect(context, sausalitoLabelRect);
            [textContent drawInRect: CGRectMake(CGRectGetMinX(sausalitoLabelRect), CGRectGetMinY(sausalitoLabelRect) + (CGRectGetHeight(sausalitoLabelRect) - sausalitoLabelTextHeight) / 2, CGRectGetWidth(sausalitoLabelRect), sausalitoLabelTextHeight) withAttributes: sausalitoLabelFontAttributes];
            CGContextRestoreGState(context);
        }


        //// Pier 41 label Drawing
        CGRect pier41LabelRect = CGRectMake(143, 304, 51, 29);
        {
            NSString* textContent = @"Pier 41";
            NSMutableParagraphStyle* pier41LabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
            pier41LabelStyle.alignment = NSTextAlignmentRight;

            NSDictionary* pier41LabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.dark, NSParagraphStyleAttributeName: pier41LabelStyle};

            CGFloat pier41LabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(pier41LabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: pier41LabelFontAttributes context: nil].size.height;
            CGContextSaveGState(context);
            CGContextClipToRect(context, pier41LabelRect);
            [textContent drawInRect: CGRectMake(CGRectGetMinX(pier41LabelRect), CGRectGetMinY(pier41LabelRect) + (CGRectGetHeight(pier41LabelRect) - pier41LabelTextHeight) / 2, CGRectGetWidth(pier41LabelRect), pier41LabelTextHeight) withAttributes: pier41LabelFontAttributes];
            CGContextRestoreGState(context);
        }


        //// Ferry Bldg label Drawing
        CGRect ferryBldgLabelRect = CGRectMake(186, 325, 51, 29);
        {
            NSString* textContent = @"Ferry Bldg";
            NSMutableParagraphStyle* ferryBldgLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
            ferryBldgLabelStyle.alignment = NSTextAlignmentRight;

            NSDictionary* ferryBldgLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.dark, NSParagraphStyleAttributeName: ferryBldgLabelStyle};

            CGFloat ferryBldgLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(ferryBldgLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: ferryBldgLabelFontAttributes context: nil].size.height;
            CGContextSaveGState(context);
            CGContextClipToRect(context, ferryBldgLabelRect);
            [textContent drawInRect: CGRectMake(CGRectGetMinX(ferryBldgLabelRect), CGRectGetMinY(ferryBldgLabelRect) + (CGRectGetHeight(ferryBldgLabelRect) - ferryBldgLabelTextHeight) / 2, CGRectGetWidth(ferryBldgLabelRect), ferryBldgLabelTextHeight) withAttributes: ferryBldgLabelFontAttributes];
            CGContextRestoreGState(context);
        }


        //// Tiburon label Drawing
        CGRect tiburonLabelRect = CGRectMake(79, 161, 51, 29);
        {
            NSString* textContent = @"Tiburon";
            NSMutableParagraphStyle* tiburonLabelStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
            tiburonLabelStyle.alignment = NSTextAlignmentRight;

            NSDictionary* tiburonLabelFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"AvenirNextCondensed-Bold" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: FerryLifeStyleKit.dark, NSParagraphStyleAttributeName: tiburonLabelStyle};

            CGFloat tiburonLabelTextHeight = [textContent boundingRectWithSize: CGSizeMake(tiburonLabelRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: tiburonLabelFontAttributes context: nil].size.height;
            CGContextSaveGState(context);
            CGContextClipToRect(context, tiburonLabelRect);
            [textContent drawInRect: CGRectMake(CGRectGetMinX(tiburonLabelRect), CGRectGetMinY(tiburonLabelRect) + (CGRectGetHeight(tiburonLabelRect) - tiburonLabelTextHeight) / 2, CGRectGetWidth(tiburonLabelRect), tiburonLabelTextHeight) withAttributes: tiburonLabelFontAttributes];
            CGContextRestoreGState(context);
        }
    }
}

+ (void)drawFerryMapIPhone6
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Symbol Drawing
    CGRect symbolRect = CGRectMake(0, 0, 375, 467);
    CGContextSaveGState(context);
    UIRectClip(symbolRect);
    CGContextTranslateCTM(context, symbolRect.origin.x, symbolRect.origin.y);
    CGContextScaleCTM(context, symbolRect.size.width / 325, symbolRect.size.height / 405);

    [FerryLifeStyleKit drawFerryMap];
    CGContextRestoreGState(context);
}

@end
